[build]
target = "wasm32-unknown-unknown"
# `leptonic` depends on some `leptos-use` functions requiring this opt-in. This may change in the future.
rustflags = ["--cfg=web_sys_unstable_apis"]


[check]
target = "wasm32-unknown-unknown"
